version: '2'

services:
    fcci:
       image: rajasoun/python:0.1
       container_name: "fcci"
       ports:
            - "5000:5000"
       volumes:
            - ~/Workspace/ck/ignitor/application/mocks/fcci:/app
       working_dir: /app
       command: "python app.py"


