version: '3.1'

services:

 start_dependencies:
     image: rajasoun/wait-for-it:0.1
     container_name: "wait-for-it"
     depends_on:
        - db
     command: db:3306
     networks:
       - back

 db:
    image: mariadb:latest
    volumes:
       - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
       - back

 wordpress:
    build: wordpress/
    depends_on:
       - db
    links:
       - db
    volumes:
      - "site-data:/var/www/wp-content"
    environment:
      WORDPRESS_SITE_URL: https://tracker.ngrok.io
      FS_METHOD: direct
      VIRTUAL_HOST: tracker.ngrok.io
      LETSENCRYPT_HOST: tracker.ngrok.io
      LETSENCRYPT_EMAIL: rajasoun@icloud.com

    networks:
      - reverse-proxy
      - back

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge

volumes:
  db-data:
  site-data:

