version: '3.1'

services:

 start_dependencies:
     image: rajasoun/wait-for-it:0.1
     container_name: "wait-for-it"
     depends_on:
        - db
     command: db:3306
     networks:
       - net

 db:
    image: mariadb:latest
    volumes:
       - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
       - net

 wordpress:
    build: wordpress/
    #build: tasks/
    #image: wordpress:latest
    depends_on:
       - db
    links:
       - db
    ports:
       - "18000:80"
    volumes:
      - "site-data:/var/www/wp-content"
    environment:
      DB_HOST: db
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      WORDPRESS_SITE_URL: https://tracker.learn.cisco
      FS_METHOD: direct
    networks:
       - net

networks:
  net:
    driver: bridge

volumes:
  db-data:
  site-data:

