version: '2'

services:

    start_dependencies:
       image: rajasoun/wait-for-it:0.1
       container_name: "wait-for-it"
       depends_on:
          - db
          - mongo
          - es
          - zookeeper
          - kafka
          - rest-proxy
          - swift
       command: db:3306 es:9200 mongo:27017 zookeeper:2181 kafka:9092 rest-proxy:8082 swift:8080

    db:
       extends:
         file: data-stores/data-stores.yml
         service: db
    mongo:
       extends:
         file: data-stores/data-stores.yml
         service: mongo

    es:
       extends:
         file: data-stores/data-stores.yml
         service: es

    zookeeper:
       extends:
         file: data-stores/data-stores.yml
         service: zookeeper

    kafka:
       extends:
         file: data-stores/data-stores.yml
         service: kafka

    rest-proxy:
       extends:
         file: data-stores/data-stores.yml
         service: rest-proxy

    swift:
       extends:
         file: data-stores/data-stores.yml
         service: swift

    ck-web:
       extends:
         file: web/site.yml
         service: ck-web

    authservice:
       extends:
         file: services/services.yml
         service: authservice

    knowledgecenter:
       extends:
         file: services/services.yml
         service: knowledgecenter

    userpi:
       extends:
         file: services/services.yml
         service: userpi

    tenantmanagement:
       extends:
         file: services/services.yml
         service: tenantmanagement

    contentstore:
       extends:
         file: services/services.yml
         service: contentstore

    pipeline:
       extends:
         file: services/services.yml
         service: pipeline

networks:
  default:
    external:
      name: clks
