version: '2'

services:

    db:
       extends:
         file: data-stores/data-stores.yml
         service: db
    mongo:
       extends:
         file: data-stores/data-stores.yml
         service: mongo

    es:
       extends:
         file: data-stores/data-stores.yml
         service: es

    zookeeper:
       extends:
         file: data-stores/data-stores.yml
         service: zookeeper

    kafka:
       extends:
         file: data-stores/data-stores.yml
         service: kafka

    rest-proxy:
       extends:
         file: data-stores/data-stores.yml
         service: rest-proxy

    swift:
       extends:
         file: data-stores/data-stores.yml
         service: swift

    ck-web:
       extends:
         file: web/web.yml
         service: ck-web

    authservice:
       extends:
         file: services/services.yml
         service: authservice

    knowledgecenter:
       extends:
         file: services/services.yml
         service: knowledgecenter

    userpi:
       extends:
         file: services/services.yml
         service: userpi

    tenantmanagement:
       extends:
         file: services/services.yml
         service: tenantmanagement

    contentstore:
       extends:
         file: services/services.yml
         service: contentstore

    pipeline:
       extends:
         file: services/services.yml
         service: pipeline

networks:
  default:
    external:
      name: clks
