version: '2'

services:
    start_dependencies:
       container_name: "wait-for-it"
       build: ./wait-for-it
       depends_on:
          - db
          - es
          - mongo
          - swift
          - kafka
          - zookeeper
       command: db:3306 es:9200 mongo:27017 swift:8080 kafka:9092 zookeeper:2181

    db:
       extends:
         file: composer/self-hosted/core.yml
         service: db
    es:
       extends:
         file: composer/self-hosted/core.yml
         service: es

    mongo:
       extends:
         file: composer/self-hosted/core.yml
         service: mongo

    zookeeper:
       extends:
         file: composer/self-hosted/zk-kafka-proxy.yml
         service: zookeeper

    kafka:
       extends:
         file: composer/self-hosted/zk-kafka-proxy.yml
         service: kafka

    rest-proxy:
       extends:
         file: composer/self-hosted/zk-kafka-proxy.yml
         service: rest-proxy

    swift:
       extends:
         file: composer/self-hosted/core.yml
         service: swift

    nginx:
       extends:
         file: composer/self-hosted/services.yml
         service: nginx

    authservice:
       extends:
         file: composer/self-hosted/services.yml
         service: authservice

    knowledgecenter:
       extends:
         file: composer/self-hosted/services.yml
         service: knowledgecenter

    userpi:
       extends:
         file: composer/self-hosted/services.yml
         service: userpi

    tenantmanagement:
       extends:
         file: composer/self-hosted/services.yml
         service: tenantmanagement

    contentstore:
       extends:
         file: composer/self-hosted/services.yml
         service: contentstore

    pipeline:
       extends:
         file: composer/self-hosted/services.yml
         service: pipeline

    docker-manager:
      extends:
        file: composer/self-hosted/devtools.yml
        service: docker-manager

    mongo-client:
      extends:
        file: composer/self-hosted/devtools.yml
        service: mongo-client

    phpmyadmin:
      extends:
        file: composer/self-hosted/devtools.yml
        service: phpmyadmin

    devtools:
      extends:
        file: composer/self-hosted/devtools.yml
        service: devtools

networks:
  default:
    external:
      name: clks
