version: '2'

services:
    db:
       extends:
         file: application/data-stores/data-stores.yml
         service: db
    mongo:
       extends:
         file: application/data-stores/data-stores.yml
         service: mongo

    es:
       extends:
         file: application/data-stores/data-stores.yml
         service: es

    zookeeper:
       extends:
         file: application/data-stores/data-stores.yml
         service: zookeeper

    kafka:
       extends:
         file: application/data-stores/data-stores.yml
         service: kafka

    rest-proxy:
       extends:
         file: application/data-stores/data-stores.yml
         service: rest-proxy

    swift:
       extends:
         file: application/data-stores/data-stores.yml
         service: swift

    ck-web:
       extends:
         file: application/web/web.yml
         service: ck-web

#    authservice:
#       extends:
#         file: composer/self-hosted/services.yml
#         service: authservice
#
#    knowledgecenter:
#       extends:
#         file: composer/self-hosted/services.yml
#         service: knowledgecenter
#
#    userpi:
#       extends:
#         file: composer/self-hosted/services.yml
#         service: userpi
#
#    tenantmanagement:
#       extends:
#         file: composer/self-hosted/services.yml
#         service: tenantmanagement
#
#    contentstore:
#       extends:
#         file: composer/self-hosted/services.yml
#         service: contentstore
#
#    pipeline:
#       extends:
#         file: composer/self-hosted/services.yml
#         service: pipeline

networks:
  default:
    external:
      name: clks
