version: '3.1'

services:

  web:
    build: web/
    container_name: "tracker.static"
    networks:
      - reverse-proxy
      - back
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=$STATIC_HOST
      - LETSENCRYPT_HOST=$STATIC_HOST
      - LETSENCRYPT_EMAIL=rajasoun@icloud.com

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge

