version: '3.1'

services:

  web:
    build: web/
    container_name: "static.web"
    networks:
      - nginx-proxy
      - net
    environment:
      - VIRTUAL_HOST=$SITE_HOST
      - LETSENCRYPT_HOST=$SITE_HOST
      - LETSENCRYPT_EMAIL=rajasoun@icloud.com

networks:
  net:
    driver: bridge
  nginx-proxy:
    external: true

