#!/usr/bin/with-contenv sh

# Terminate on Errors
set -e
echo 'Configuring Wordpress'

wp core install --path=/usr/src/wordpress/ \
         --url=https://tracker.learn.cisco/tasks \
         --title="Tracker" --admin_user=admin \
         --admin_password=vziMjlWd3^RoZRO%i# \
         --admin_email=rajasoun@icloud.com  --allow-root

wp cli update --path=/usr/src/wordpress/ --allow-root
