version: '2'

services:

    nginx:
        container_name: "ckweb"
        build: ../../nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ~/Workspace/ck/cheetah/knowledgecenter/kc-web/src/main/webapp:/www/knowledgecenter

    authservice:
        container_name: "authservice"
        image: anapsix/alpine-java:latest
        ports:
            - "8006:8006"
        volumes:
            - ~/Workspace/ck/cheetah/authorization:/app
            - ~/Workspace/ck/cheetah/ignitor/backbone/workers/scripts:/etc/b2b/scripts
        working_dir: /app
        command: "/etc/b2b/scripts/start.sh authorization 8006 authorization"
        environment:
            - jdbc.url=jdbc:mysql://ckdb:3306/b2b

    knowledgecenter:
        container_name: "knowledgecenter"
        image: anapsix/alpine-java:latest
        ports:
            - "8002:8002"
        volumes:
            - ~/Workspace/ck/cheetah/knowledgecenter:/app
            - ~/Workspace/ck/cheetah/ignitor/backbone/workers/override-properties/kc:/etc/b2b/properties
            - ~/Workspace/ck/cheetah/ignitor/backbone/workers/scripts:/etc/b2b/scripts
        working_dir: /app
        environment:
            CLASSPATH: /etc/b2b/properties
        command: "/etc/b2b/scripts/start.sh kc 8002 knowledgecenter"


    userpi:
        container_name: "userpi"
        image: anapsix/alpine-java:latest
        ports:
            - "8005:8005"
        volumes:
            - ~/Workspace/ck/cheetah/userpi:/app
            - ~/Workspace/ck/cheetah/ignitor/backbone/workers/override-properties/userpi:/etc/b2b/properties
            - ~/Workspace/ck/cheetah/ignitor/backbone/workers/scripts:/etc/b2b/scripts
        working_dir: /app
        environment:
            CLASSPATH: /etc/b2b/properties
        command: "/etc/b2b/scripts/start.sh userpi 8005 userpi"

    tenantmanagement:
        container_name: "tenantmanagement"
        image: anapsix/alpine-java:latest
        ports:
            - "8010:8010"
        volumes:
            - ~/Workspace/ck/cheetah/tenantmanagement:/app
            - ~/Workspace/ck/cheetah/ignitor/backbone/workers/override-properties/tenantmanagement:/etc/b2b/properties
            - ~/Workspace/ck/cheetah/ignitor/backbone/workers/scripts:/etc/b2b/scripts
        working_dir: /app
        environment:
            CLASSPATH: /etc/b2b/properties
        command: "/etc/b2b/scripts/start.sh tm 8010 tenantmanagement"

    contentstore:
         container_name: "contentstore"
         image: anapsix/alpine-java:latest
         ports:
            - "8003:8003"
         volumes:
            - ~/Workspace/ck/cheetah/tenantmanagement:/app
            - ~/Workspace/ck/cheetah/ignitor/backbone/workers/override-properties/contentstore:/etc/b2b/properties
            - ~/Workspace/ck/cheetah/ignitor/backbone/workers/scripts:/etc/b2b/scripts
         working_dir: /app
         environment:
             CLASSPATH: /etc/b2b/properties
         command: "/etc/b2b/scripts/start.sh contentstore 8003 contentstore"
