version: '2'

services:

  nginx:
    container_name: "ckweb"
    build: ../../nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/Workspace/ck/cheetah/knowledgecenter/kc-web/src/main/webapp:/www/knowledgecenter

  authservice:
    image: rajasoun/java:0.1
    container_name: "authservice"
    ports:
       - "8006:8006"
    volumes:
       - ~/Workspace/ck/cheetah/authorization:/app
       - ~/Workspace/ck/ignitor/application/workers/override-properties/authorization:/etc/b2b/properties
       - ~/Workspace/ck/ignitor/application/workers/scripts:/etc/b2b/scripts
    working_dir: /app
    environment:
        jdbc.url: jdbc:mysql://ckdb:3306/b2b
        CLASSPATH: /etc/b2b/properties
    command: "/etc/b2b/scripts/start.sh authorization 8006 authorization"

  knowledgecenter:
    container_name: "knowledgecenter"
    image: rajasoun/java:0.1
    ports:
       - "8002:8002"
    volumes:
       - ~/Workspace/ck/cheetah/knowledgecenter:/app
       - ~/Workspace/ck/ignitor/application/workers/override-properties/kc:/etc/b2b/properties
       - ~/Workspace/ck/ignitor/application/workers/scripts:/etc/b2b/scripts
    working_dir: /app
    environment:
        CLASSPATH: /etc/b2b/properties
    command: "/etc/b2b/scripts/start.sh kc 8002 knowledgecenter"

  userpi:
    container_name: "userpi"
    image: rajasoun/java:0.1
    ports:
       - "8005:8005"
    volumes:
       - ~/Workspace/ck/cheetah/userpi:/app
       - ~/Workspace/ck/ignitor/application/workers/override-properties/userpi:/etc/b2b/properties
       - ~/Workspace/ck/ignitor/application/workers/scripts:/etc/b2b/scripts
    working_dir: /app
    environment:
        CLASSPATH: /etc/b2b/properties
    command: "/etc/b2b/scripts/start.sh userpi 8005 userpi"

  tenantmanagement:
    container_name: "tenantmanagement"
    image: rajasoun/java:0.1
    ports:
       - "8010:8010"
    volumes:
       - ~/Workspace/ck/cheetah/tenantmanagement:/app
       - ~/Workspace/ck/ignitor/application/workers/override-properties/tenantmanagement:/etc/b2b/properties
       - ~/Workspace/ck/ignitor/application/workers/scripts:/etc/b2b/scripts
    working_dir: /app
    environment:
        CLASSPATH: /etc/b2b/properties
    command: "/etc/b2b/scripts/start.sh tm 8010 tenantmanagement"

  contentstore:
    container_name: "contentstore"
    image: rajasoun/java:0.1
    ports:
       - "8003:8003"
    volumes:
       - ~/Workspace/ck/cheetah/contentstore:/app
       - ~/Workspace/ck/ignitor/application/workers/override-properties/contentstore:/etc/b2b/properties
       - ~/Workspace/ck/ignitor/application/workers/scripts:/etc/b2b/scripts
    working_dir: /app
    environment:
        CLASSPATH: /etc/b2b/properties
    command: "/etc/b2b/scripts/start.sh contentstore 8003 contentstore"

  pipeline:
    container_name: "pipeline"
    image: rajasoun/java:0.1
    ports:
       - "8001:8001"
    volumes:
       - ~/Workspace/ck/cheetah/pipeline:/app
       - ~/Workspace/ck/ignitor/application/workers/override-properties/pipeline:/etc/b2b/properties
       - ~/Workspace/ck/ignitor/application/workers/scripts:/etc/b2b/scripts
    working_dir: /app
    environment:
        CLASSPATH: /etc/b2b/properties
    command: "/etc/b2b/scripts/start.sh pipeline 8001 pipeline"
