version: '3.1'
services:
  nginx:
    build: nginx/
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
    networks:
      - net
    environment:
      VIRTUAL_HOST: tracker.learn.cisco

    networks:
       - reverse-proxy
       - back

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge

