version: '3'

services:

  start_dependencies:
     image: rajasoun/wait-for-it:0.1
     depends_on:
        - orientdb
     command: orientdb:2424
     networks:
       - net

  orientdb:
     #build: orientdb/
     image: orientdb:3.0.0m1
     ports:
        - "2424:2424"
        - "2480:2480"
     environment:
        ORIENTDB_ROOT_PASSWORD: admin
     networks:
        - net
#
#  scanner:
#     build: scanner/
#     depends_on:
#       - orientdb
#     networks:
#       - net

networks:
  net:
    driver: bridge
