#!/usr/bin/with-contenv sh

PUID=${PUID:-911}
PGID=${PGID:-911}

addgroup -g "$PGID" -S db
adduser -h /var/log/db -g db  -G db -S -u "$PUID" db
##:TODO : CleanUp
#adduser -h /var/log/db -g db -s /sbin/nologin -G db -S -u 911 db

# Create  folders
mkdir -p \
  /app \
  /config \
  /defaults && \

chown db:db /app
chown db:db /config
chown db:db /defaults
