version: '2'
services:
  nginx:
    build: nginx/
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
    networks:
      - proxy_net

networks:
  proxy_net:
    driver: bridge
