version: '2'

services:
  db:
    image: mariadb:10.1
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  tasks:
    depends_on:
      - db
    build: tasks/
    volumes:
      - "site-data:/var/www/wp-content"
    links:
      - db
    ports:
      - "28000:80"
    environment:
      DB_HOST: db
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      DB_USER: wordpress
      WORDPRESS_SITE_URL: https://tracker.learn.cisco
      FS_METHOD: direct

volumes:
  db-data:
  site-data:
