version: '2'

services:
  devtools:
     container_name: "devtools"
     build: swiftclient/

  mongo-client:
     container_name: "mongo-client"
     image: mongoclient/mongoclient
     ports:
       - "13000:3000"
     environment:
       MONGO_URL: mongodb://ckmongo:27017/b2b
       LOGSPOUT: ignore

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin/phpmyadmin
    ports:
      - "18080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306


