version: "2"

services:
  nginx:
    build: nginx/
    container_name: "cachet-web"
    ports:
      - 8787:80
    links:
      - cachet
    volumes_from:
      - cachet
    depends_on:
      - cachet
    networks:
      - local

  postgres:
    image: postgres:9.5
    container_name: "cachet-db"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cachet:
    #image: cachethq/docker:2.3.10
    image: cachethq/docker
    container_name: "cachet-server"
    expose:
      - 9000
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    volumes:
      - /var/www
    depends_on:
      - postgres
    networks:
      - local
