version: '2'

services:
  hubot:
    build: .
    container_name: ops-bot
    restart: always
    volumes:
      - ./scripts:/hubot/scripts
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - HUBOT_PORT=8080
      - HUBOT_ADAPTER=slack
      - HUBOT_NAME=ops-bot
      - HUBOT_SLACK_TOKEN=@token
      - HUBOT_AUTH_ADMIN=U06LZSRD0
      - HUBOT_UPTIMEROBOT_APIKEY=@roken
      - REDIS_URL=redis://redis:6379
    links:
      - redis
    command: ./bin/hubot -a slack
    networks:
      - chat_ops

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis:/data
      - /etc/localtime:/etc/localtime:ro
    command: redis-server --appendonly yes
    networks:
      - chat_ops

networks:
  chat_ops:
    driver: bridge
