version: '2'

services:
    start_dependencies:
       image: rajasoun/wait-for-it:0.1
       container_name: "wait-for-it"
       depends_on:
          - db
          - mongo
          - es
          - zookeeper
          - kafka
          - rest-proxy
          - swift
       command: db:3306 es:9200 mongo:27017 zookeeper:2181 kafka:9092 rest-proxy:8082 swift:8080

    db:
        build: mariadb/
        container_name: "ckdb"
        ports:
          - "3306:3306"
        volumes:
          - ~/Workspace/ck/ignitor/application/data-stores/setup/initdb:/initdb
        environment:
          - MASTER_PASSWORD=password@1234
          - MARIADB_DATABASE=b2b
          - MARIADB_USER=ckuser
          - MARIADB_PASSWORD=Cisco@1234

    mongo:
        build: mongodb/
        container_name: "ckmongo"
        ports:
          - "27017:27017"

    es:
        build: elasticsearch/
        container_name: "ckes"
        ports:
          - "9200:9200"
          - "9300:9300"

    zookeeper:
        image: confluent/zookeeper
        container_name: "zookeeper"
        ports:
          - "2181:2181"
        environment:
          zk_id: "1"

    kafka:
        image: confluent/kafka
        container_name: "kafka"
        ports:
          - "9092:9092"
        environment:
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

    rest-proxy:
        image: confluent/rest-proxy
        container_name: "rest-proxy"
        ports:
          - "8082:8082"
        environment:
          RP_ZOOKEEPER_CONNECT: "zookeeper:2181"

    swift:
         image: "morrisjobke/docker-swift-onlyone"
         container_name: "ckswift"
         ports:
            - "8080"
         environment:
            - LOGSPOUT=ignore
