version: '2'

services:

    logspout:
      container_name: "logspout"
      image: gliderlabs/logspout:v3
      command: 'syslog://logstash:5000'
      links:
        - logstash
      volumes:
        - '/var/run/docker.sock:/tmp/docker.sock'

    logstash:
      container_name: "logstash"
      image: ludekvesely/logstash-json
      environment:
        - LOGSPOUT=ignore
        - DROP_NON_JSON=false
        - STDOUT=true
      links:
        - elasticsearch

    kibana:
      container_name: "kibana"
      image: docker.elastic.co/kibana/kibana:5.2.2
      environment:
        - LOGSPOUT=ignore
      links:
        - elasticsearch
      ports:
        - '5601:5601'

    elasticsearch:
      container_name: "elasticsearch"
      image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
      environment:
        - LOGSPOUT=ignore
