#!/usr/bin/with-contenv sh

mkdir /run/clamav
chown clamav:clamav /run/clamav


chown clamav:clamav /var/lib/clamav/*.cvd

sed -i 's/^#Foreground .*$/Foreground true/g' /etc/clamav/clamd.conf
sed -i 's/^#TCPSocket .*$/TCPSocket 3310/g' /etc/clamav/clamd.conf
sed -i 's/^#Foreground .*$/Foreground true/g' /etc/clamav/freshclam.conf
