#!/usr/bin/with-contenv sh

# initial update of av databases
wget -O /var/lib/clamav/main.cvd http://database.clamav.net/main.cvd
wget -O /var/lib/clamav/daily.cvd http://database.clamav.net/daily.cvd
wget -O /var/lib/clamav/bytecode.cvd http://database.clamav.net/bytecode.cvd
chown clamav:clamav /var/lib/clamav/*.cvd

# permission juggling
mkdir -p /var/run/clamav
chown clamav:clamav /var/run/clamav
chmod 750 /var/run/clamav

