version: '2'

services:
    base:
        build: base/
        container_name: "rajasoun/base:0.1"
    java:
        build: java/
        container_name: "rajasoun/java:0.1"
    python:
        build: python/
        container_name: "rajasoun/python:0.1"
    wait-for-it:
        build: wait-for-it/
        container_name: "rajasoun/wait-for-it:0.1"
    ansible:
        build: ansible/
        container_name: "rajasoun/ansible:0.1"
