version: '2'

services:
  nginx:
    build: nginx/
    container_name: "nginx-proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d

  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local

