version: '3.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'nginx-certs:/etc/nginx/conf.d:ro'
      - 'nginx-conf:/etc/nginx/conf.d'
      - 'nginx-contents:/usr/share/nginx/html'
      - 'nginx-logs:/var/log/nginx'
      - 'nginx-vhost:/etc/nginx/vhost.d'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    networks:
       - reverse-proxy

  letsencrypt-nginx-proxy:
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    container_name: nginx-letsencrypt
    volumes:
      - 'nginx-certs:/etc/nginx/conf.d:rw'
      - 'nginx-conf:/etc/nginx/conf.d:nocopy'
      - 'nginx-vhost:/etc/nginx/vhost.d'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

    networks:
       - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

volumes:
  nginx-certs: {}
  nginx-conf: {}
  nginx-vhost: {}
  nginx-contents: {}
  nginx-logs: {}
