version: '3'
services:

  web:
    image: nginx:alpine
    container_name: static-site
    environment:
      VIRTUAL_HOST: static-site.ngrok.io
      LETSENCRYPT_HOST: static-site.ngrok.io
      LETSENCRYPT_EMAIL: rajasoun@icloud.com
    networks:
      - reverse-proxy
      - back

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    ports:
      - "0.0.0.0:4040:4040"
    links:
      - web
    environment:
      - NGROK_AUTH=5ZqthG6vijSovhHym3LFt_4ie6bHaKUTkRD7QAd17mp
      - NGROK_PORT=web:80
      - NGROK_PROTOCOL=HTTP
      - NGROK_SUBDOMAIN=static-site
    networks:
      - reverse-proxy
      - back

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge
