version: '3.1'

services:
  app:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
      - nginx-proxy
    environment:
       VIRTUAL_HOST: $PORTAINER_HOST
       LETSENCRYPT_EMAIL: rajasoun@icloud.com
       LETSENCRYPT_HOST: $PORTAINER_HOST
       LOGSPOUT: ignore

  watchtower:
    image: centurylink/watchtower
    command: --cleanup portainer-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    environment:
       LOGSPOUT: ignore

networks:
  net:
    driver: bridge
  nginx-proxy:
    external: true
