version: '2'

services:
  proxy:
    build: nginx/
    container_name: "portainer-web"
    networks:
      - docker_manager
      - reverse-proxy
    environment:
       LETSENCRYPT_EMAIL: rajasoun@icloud.com
       LETSENCRYPT_HOST: portainer.myck.io
       VIRTUAL_HOST: portainer.myck.io
       VIRTUAL_PORT: 80
       LOGSPOUT: ignore

  templates:
    build: templates/
    container_name: "portainer-templates"
    networks:
      - docker_manager
    environment:
       LOGSPOUT: ignore

  portainer:
    image: portainer/portainer
    container_name: "portainer-server"
    command: --templates http://templates/templates.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data
    networks:
      - docker_manager
    environment:
       LOGSPOUT: ignore

  watchtower:
    image: centurylink/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_manager

networks:
  docker_manager:
    driver: bridge

  reverse-proxy:
    external:
      name: reverse-proxy

