version: '2'

services:

  es:
    container_name: "ckes"
    build: ../../elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  db:
    container_name: "ckdb"
    build: ../../mariadb
    ports:
      - "3306:3306"
    volumes:
      - ~/Workspace/ck/devbox-docker/backbone/workers/initdb:/initdb
    environment:
      - MASTER_PASSWORD=password@1234
      - MARIADB_DATABASE=b2b
      - MARIADB_USER=ckuser
      - MARIADB_PASSWORD=Cisco@1234

  mongo:
    container_name: "ckmongo"
    build: ../../mongodb
    ports:
      - "27017:27017"


  kafka:
    container_name: "kafka"
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.10.10.1
      KAFKA_ADVERTISED_PORT: 9092

  swift:
     container_name: "ckswift"
     image: "morrisjobke/docker-swift-onlyone"
     ports:
        - "8080"
     environment:
        - LOGSPOUT=ignore
