version: '2'

services:

  nginx:
    container_name: "ckweb"
    build: ../../nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/Workspace/ck/platform/knowledgecenter/kc-web/src/main/webapp:/www/knowledgecenter

  authservice:
    image: rajasoun/java:0.1
    container_name: "authservice"
    ports:
       - "8006:8006"
    volumes:
       - ~/Workspace/ck/platform/authorization:/app
       - ~/Workspace/ck/devbox-docker/backbone/workers/scripts:/etc/b2b/scripts
    working_dir: /app
    command: "/etc/b2b/scripts/start.sh authorization 8006 authorization"
    environment:
        - jdbc.url=jdbc:mysql://ckdb:3306/b2b

  knowledgecenter:
    container_name: "knowledgecenter"
    image: rajasoun/java:0.1
    ports:
       - "8002:8002"
    volumes:
       - ~/Workspace/ck/platform/knowledgecenter:/app
       - ~/Workspace/ck/devbox-docker/backbone/workers/override-properties/kc:/etc/b2b/properties
       - ~/Workspace/ck/devbox-docker/backbone/workers/scripts:/etc/b2b/scripts
    working_dir: /app
    environment:
        CLASSPATH: /etc/b2b/properties
    command: "/etc/b2b/scripts/start.sh kc 8002 knowledgecenter"

  userpi:
    container_name: "userpi"
    image: rajasoun/java:0.1
    ports:
       - "8005:8005"
    volumes:
       - ~/Workspace/ck/platform/userpi:/app
       - ~/Workspace/ck/devbox-docker/backbone/workers/override-properties/userpi:/etc/b2b/properties
       - ~/Workspace/ck/devbox-docker/backbone/workers/scripts:/etc/b2b/scripts
    working_dir: /app
    environment:
        CLASSPATH: /etc/b2b/properties
    command: "/etc/b2b/scripts/start.sh userpi 8005 userpi"
                                                         x
  tenantmanagement:
    container_name: "tenantmanagement"
    image: rajasoun/java:0.1
    ports:
       - "8010:8010"
    volumes:
       - ~/Workspace/ck/platform/tenantmanagement:/app
       - ~/Workspace/ck/devbox-docker/backbone/workers/override-properties/tenantmanagement:/etc/b2b/properties
       - ~/Workspace/ck/devbox-docker/backbone/workers/scripts:/etc/b2b/scripts
    working_dir: /app
    environment:
        CLASSPATH: /etc/b2b/properties
    command: "/etc/b2b/scripts/start.sh tm 8010 tenantmanagement"
