version: '2'

services:

  docker-manager:
     container_name: "docker-manager"
     image: portainer/portainer
     ports:
       - "9001:9001"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock

  devtools:
    container_name: "devtools"
    build: ../../devtools

  mongo-client:
     container_name: "mongo-client"
     image: mongoclient/mongoclient
     ports:
       - "3000:3000"
     environment:
       - MONGO_URL: "mongodb://ckmongo:27017/b2b"

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306


