version: "2"
services:
  zookeeper:
    image: confluent/zookeeper
    container_name: "zookeeper"
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka:
    image: confluent/kafka
    container_name: "kafka"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

  rest-proxy:
    image: confluent/rest-proxy
    container_name: "rest-proxy"
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8082:8082"
    environment:
      RP_ZOOKEEPER_CONNECT: "zookeeper:2181"
