version: '3.1'

services:
  app:
    image: hopsoft/graphite-statsd
    ports:
      - "9101:9101"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"

    networks:
      - net
      - nginx-proxy

    environment:
       VIRTUAL_HOST: $STATSD_HOST
       LETSENCRYPT_EMAIL: rajasoun@icloud.com
       LETSENCRYPT_HOST: $STATSD_HOST

networks:
  net:
    driver: bridge
  nginx-proxy:
    external: true
