version: '2'

services:

  nginx:
    container_name: "ckweb"
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/Workspace/ck/platform/knowledgecenter/kc-web/src/main/webapp:/www/knowledgecenter

  es:
    container_name: "ckes"
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  db:
    container_name: "ckdb"
    build: ./mariadb
    ports:
      - "3306:3306"
    environment:
      - MASTER_PASSWORD=password@1234
      - MARIADB_DATABASE=b2b
      - MARIADB_USER=ckuser
      - MARIADB_PASSWORD=Cisco@1234

  mongo:
    container_name: "ckmongo"
    build: ./mongodb
    ports:
      - "27017:27017"

  genghis:
    container_name: "devtools"
    build: ./devtools
    links:
      - mongo:db
    ports:
      - "5678:5678"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8080:80'

  authservice:
    image: rajasoun/java:0.1
    container_name: "authservice"
    working_dir: /app
    volumes:
       - ~/Workspace/ck/platform/authorization:/app
    command: ./run.sh
    ports:
       - "8006:8006"
    links:
      - db
    depends_on:
        - db

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:3306

#  portainer:
#     container_name: "portainer"
#     image: portainer/portainer
#     ports:
#       - "9001:9001"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock

