version: '2'

services:

  start_dependencies:
    container_name: "wait-for-it"
    build: ./wait-for-it
    depends_on:
      - db
      - es
      - mongo
    command: db:3306 es:9200 mongo:27017

  nginx:
    container_name: "ckweb"
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/Workspace/ck/platform/knowledgecenter/kc-web/src/main/webapp:/www/knowledgecenter

  es:
    container_name: "ckes"
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  db:
    container_name: "ckdb"
    build: ./mariadb
    ports:
      - "3306:3306"
    environment:
      - MASTER_PASSWORD=password@1234
      - MARIADB_DATABASE=b2b
      - MARIADB_USER=ckuser
      - MARIADB_PASSWORD=Cisco@1234

  mongo:
    container_name: "ckmongo"
    build: ./mongodb
    ports:
      - "27017:27017"

  genghis:
    container_name: "devtools"
    build: ./devtools
    ports:
      - "5678:5678"
    links:
      - mongo

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    links:
      - db


  authservice:
    image: rajasoun/java:0.1
    container_name: "authservice"
    ports:
       - "8006:8006"
    volumes:
       - ~/Workspace/ck/platform/authorization:/app
    working_dir: /app
    command: ./run.sh
    environment:
        - jdbc.url=jdbc:mysql://ckdb:3306/b2b
    links:
      - db
    depends_on:
      - db

  knowledgecenter:
    container_name: "knowledgecenter"
    #image: openjdk:8
    image: anapsix/alpine-java:latest
    ports:
       - "8002:8002"
    volumes:
       - ~/Workspace/ck/platform/knowledgecenter:/app
    working_dir: /app
    command: ./run.sh
    links:
      - mongo
    depends_on:
      - mongo

#  portainer:
#     container_name: "portainer"
#     image: portainer/portainer
#     ports:
#       - "9001:9001"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock

