version: '2'

services:
  base:
    container_name: "base"
    build: ./base


  java:
    container_name: "java"
    build: ./java

  es:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"


  db:
    container_name: "ckdb"
    build: ./mariadb
    ports:
      - "3306:3306"

