version: '2'

services:
    start_dependencies:
       container_name: "wait-for-it"
       build: ./wait-for-it
       depends_on:
          - db
          - es
          - mongo
          - swift
       command: db:3306 es:9200 mongo:27017 swift:8080

    db:
       extends:
         file: composer/third-party/backbone.yml
         service: db
    es:
       extends:
         file: composer/third-party/backbone.yml
         service: es
    mongo:
       extends:
         file: composer/third-party/backbone.yml
         service: mongo
    swift:
       extends:
         file: composer/third-party/backbone.yml
         service: swift

    nginx:
       extends:
         file: composer/third-party/ck-services.yml
         service: nginx

    authservice:
       extends:
         file: composer/third-party/ck-services.yml
         service: authservice

    knowledgecenter:
       extends:
         file: composer/third-party/ck-services.yml
         service: knowledgecenter

    userpi:
       extends:
         file: composer/third-party/ck-services.yml
         service: userpi

    tenantmanagement:
       extends:
          file: composer/third-party/ck-services.yml
          service: tenantmanagement

    contentstore:
        extends:
          file: composer/third-party/ck-services.yml
          service: contentstore

    pipeline:
        extends:
          file: composer/third-party/ck-services.yml
          service: pipeline
