version: "2"

services:
  url-monitor:
    image: golang:1.8-alpine
    container_name: "cachet-url-monitor"
    volumes:
      - ~/Workspace/ck/ignitor/ops-tools/cachet/url-monitor:/app
    working_dir: /app
    command: entrypoint.sh
