version: "2"

services:
  url-monitor:
    image: golang:1.8-alpine
    container_name: "cachet-url-monitor"
    volumes:
      - ~/ignitor/ops-tools/cachet/url-monitor:/go/src/app
    working_dir: /go/src/app
    command: entrypoint.sh
