version: '3.1'

services:

  tracker:
    build: tracker/
    container_name: "tracker.static"
    environment:
      VIRTUAL_HOST: tracker.learn.cisco
    networks:
      - reverse-proxy
      - back

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge

