version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '~/etc/nginx/certs:/etc/nginx/certs:ro'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'

  letsencrypt-nginx-proxy:
    container_name: letsencrypt-nginx-proxy
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    volumes:
      - '~/etc/nginx/certs:/etc/nginx/certs'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    volumes_from:
      - nginx-proxy

  ghost:
    image: gold/ghost
    command: npm start --production
    restart: always
    ports:
        - "2368:2368"
    volumes:
        - ~/blog/:/var/lib/ghost
    environment:
        - GHOST_URL=http://gold-ghost.ngrok.io
        - VIRTUAL_HOST=gold-ghost.ngrok.io
        - LETSENCRYPT_HOST=gold-ghost.ngrok.io
        - LETSENCRYPT_EMAIL=rajasoun@icloud.com
        - PROD_FORCE_ADMIN_SSL=true

networks:
  default:
    external:
      name: nginx-net
