version: '2'
services:
  tracker-docs:
    build: hugo/
    container_name: tracker-docs
    ports:
      - "1313:1313"
    networks:
      - tracker_docs_net

networks:
  tracker_docs_net:
    driver: bridge
