version: '2'
services:
  tracker:
    build: hugo/
    ports:
      - "9100:1313"
    networks:
      - tracker_net
    environment:
      - HUGO_WATCH=true

networks:
  tracker_net:
    driver: bridge
