version: '2'

services:
    logspout:
      image: gliderlabs/logspout:v3
      command: 'syslog://logstash:5000'
      volumes:
        - '/var/run/docker.sock:/tmp/docker.sock'

    logstash:
      image: ludekvesely/logstash-json
      environment:
        - LOGSPOUT=ignore
        - DROP_NON_JSON=false
        - STDOUT=true

    kibana:
      image: kibana
      environment:
        - LOGSPOUT=ignore
      ports:
        - '5601:5601'

    elasticsearch:
      image: elasticsearch
      environment:
        - LOGSPOUT=ignore

